#!/bin/bash

echo "Instructions to push your code to GitHub:"
echo ""
echo "1. Create a new repository on GitHub (don't initialize it)"
echo "2. Replace YOUR_GITHUB_USERNAME with your actual username"
echo "3. Run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_GITHUB_USERNAME/gabstep-business-chat.git"
echo "git branch -M main"
echo "git merge feature/gabstep-business-chat-implementation --no-ff"
echo "git push -u origin main"
echo "git push origin feature/gabstep-business-chat-implementation"
echo ""
echo "Then on your local machine:"
echo "git clone https://github.com/YOUR_GITHUB_USERNAME/gabstep-business-chat.git"
echo "cd gabstep-business-chat"
echo "npm install"
echo "npm run dev"
